Projects/Career-Crafters/assets/css/bookmarks.css
Projects/Career-Crafters/assets/css/contact.css
Projects/Career-Crafters/assets/css/notification.css
Projects/Career-Crafters/assets/css/progress.css
Projects/Career-Crafters/index.html
Projects/Career-Crafters/styles.css

Title : Feature_Request #6 
Issue No. : 6
Code Stack :  HTML and CSS
Close #6 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

Made some UI improvements to the Career-Crafters project folder

---

Index.html.md

Revert "Update Index.html.md"

---

Index.html.md
Projects/URL SHORTENER/Readme.md
Projects/URL SHORTENER/index.html
Projects/URL SHORTENER/script.js
Projects/URL SHORTENER/style.css

Title : Url Shortener
Issue No. : #72
Code Stack 👍 
- I am a contributor in HACTOBERFEST 2023

Geeks arpan patch 1 1

---

Index.html.md

Title :
Issue No. :
Code Stack : 

Updated index.html.md

---

Index.html.md
Projects/Score Keeper/Readme.md
Projects/Score Keeper/index.html
Projects/Score Keeper/script.js
Projects/Score Keeper/style.css

Title : Score Keeper Project
Issue No. : #89 
Code Stack 👍 
Close #89 
- I am a contributor in HACKTOBERFEST 2023

Score keeper

---

Index.html.md
Projects/Code Editor/Readme.md
Projects/Code Editor/index.html
Projects/Code Editor/script.js
Projects/Code Editor/style.css

Title : Code Editor Project
Issue No. : #106 
Code Stack 👍 
Close #106
https://github.com/apu52/METAVERSE/assets/99377659/292b5f7c-3d89-4e0b-939b-ec72ca8bc2f3
- 

Code editor

---

README.md

Title : Fixed the contribution section in README file
Issue No. : 114
Code Stack : 
Close #114 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

Fixed the contribution section in README.md

---

Projects/Age Calculator/index.html
Projects/Age Calculator/script.js
Projects/Age Calculator/style.css

Title :  added a new feature to display age in year, months and days
Issue No. : #121
ref: #121 
Code Stack :

 added a new feature to display age in year, months and days

---

Projects/Age Calculator/index.html
Projects/Age Calculator/script.js
Projects/Age Calculator/style.css

Title : added a reset button to reset the date
Issue No. :
ref #124

added a reset button to reset the date

---

Index.html.md
Projects/Meme Generator/Readme.md
Projects/Meme Generator/index.html
Projects/Meme Generator/script.js
Projects/Meme Generator/style.css

Title : Meme Generator
Issue No. : #132
Code Stack 👍 
Close #132 
https://github.com/apu52/METAVERSE/assets/99377659/79465a51-9122-4f20-b924-f906166def3b
**Additional context (Mandatory )** 

Meme generator

---

Projects/Myntra Clone Website/Contact.html
Projects/Myntra Clone Website/about.html
Projects/Myntra Clone Website/blog.html
Projects/Myntra Clone Website/cart.html
Projects/Myntra Clone Website/index.html
Projects/Myntra Clone Website/shop.html
Projects/Myntra Clone Website/sproduct.html

Title : Myntra Clone Project
Issue No. : #139 
Code Stack 👍 
Close #139 
https://github.com/apu52/METAVERSE/assets/99377659/4ced4675-09ba-49ca-bb5f-1ccf7797db59
- I have commented my code, particularly in hard-to-understand area

Myntra clone project

---

Index.html.md
Projects/Quote Generator/Readme.md
Projects/Quote Generator/index.html
Projects/Quote Generator/script.js
Projects/Quote Generator/style.css

Title : Quote of the Day
Issue No. :#143
Code Stack 👍 
Close #143
https://github.com/apu52/METAVERSE/assets/99377659/63a2285b-afcd-44c6-b86f-4f3862b593c4

Quote generator

---

Projects/Age_Calculator/index.html
Projects/Age_Calculator/script.js

Title :Displayed the age in dog years 
Issue No. :151
ref #151 
I have added the feature to display the age in dog years .
I am an OSEN contributor

displayed the age in dog years

---

assets/css/contributors.css

Title : Centering contributor list
Issue No. : #170 
Code Stack : html
Close #170  
CodePeak'23

Aligned items to center

---

assets/css/cursor_transition.css
assets/js/mouse_transition.js
index.html

Title : Mouse Transition Effect
Issue No. : #178 
Code Stack : HTML, CSS and JavaScript
Close #178 
https://github.com/apu52/METAVERSE/assets/95460188/ee813a06-a3b1-407e-ae73-f0a5dad4bf72
Yes, i am contributing under KWOC 2023 and CodePeak 2023.

Mouse Transition effect 

---

Projects/Code_Editor/index.html
Projects/Code_Editor/script.js
Projects/Code_Editor/style.css

Title : Code editor Mobile friendly
Issue No. : #189 
Code Stack : javascript css html monaco editor 
Close #189 
https://github.com/apu52/METAVERSE/assets/111063866/244f0870-2e1b-4806-be84-83ff6e69d5f0
Accessibility: Mobile-friendly design allows users to access and use your code editor from smartphones or tablets, increasing accessibility and user reach.
Wider Audience Reach: With the increasing use of mobile devices, having a mobile-friendly code editor enables users to write and edit code on the go, appealing to a broader audience.
Improved User Experience: Optimizing the layout, interface, and functionality for mobile devices enhances the user experience. Users can comfortably interact with the editor, write code, and perform necessary tasks even …

Made Code editor Mobile friendly

---

Projects/Book_review_website/style.css

Title : Hamburger menu website items not visible- Book review website
Issue No. : #200 
Code Stack : CSS
Close #200 
CodePeak'23

Edited Hamburger menu contents fontcolor and added transition effect 

---

Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/index.js
Projects/Food_Ordering_Website/style.css

Title :Responsiveness Problem in Food_Ordering_Website
Issue No. :#203
Code Stack :  html, css, Javascript
Close #203 
I am putting up some references related to what Changes I made
KWOC 2023

Responsiveness Problem in Food_Ordering_Website

---

Projects/Hackathons/css/responsive.css
Projects/Hackathons/css/style.css
Projects/Hackathons/index.html

Title :Improvement in the UI of the navbar of Hackathon website.
Fixes #196 
Issue No. :#196
I have improved the UI of the Hackathon website's navbar with the help of Bootstrap CSS componenets.The navbar is also responsive.
Close #<issue_no>196
Screenshot:
<br>

Feat hackathon-nav

---

Projects/Book_review_website/index.html
Projects/Book_review_website/style.css

Title : Book review web Responsive UI
Issue No. :#195
Close:  #195
yes CODEPEAK'23

book review responsive UI2

---

Projects/Calendar/index.html
Projects/Calendar/style.css

Toggle button is now made visible. 
Fixes #236 
Title :Toggle button is now made visible. 
Issue No. : #236 
Screenshot:
<br>

Fix: toggle button in Calendar-web-app.

---

Projects/Hackathons/about.html
Projects/Hackathons/index.html

About page created for Hack Among Us website.
Fixes #235 
Title :About page created for Hack Among Us website.
Issue No. :#235
Screenshot:

Feat about hackathon

---

Projects/Code_Editor/package.json
Projects/To-Do_List_Project/features.html
Projects/To-Do_List_Project/index.html
Projects/To-Do_List_Project/pricing.html
Projects/To-Do_List_Project/styles.css

Title :
UI of To -DO list app updated
Issue No. :
#254 
Code Stack : 
HTML,CSS, Javascript
Close #254 
https://github.com/apu52/METAVERSE/assets/68018372/6cd21751-2958-4036-8cc2-003acd9cc29a

UI updated for To-do list

---

Projects/Hackathons/contact.html
Projects/Hackathons/index.html

Title :
Making changes to UI using bootstrap for Hackathons website
Issue No. : #271 
Code Stack : 
Html,css, bootstrap, javascript
Close #271
https://github.com/apu52/METAVERSE/assets/68018372/fffa3e17-0470-4ea8-8084-3c2a5d63b049
CodePeak

made suggested changes

---

assets/css/style.css
contact.html

Title : Redesign Metaverse Contact Us Page
Issue No. :#281
Code Stack :  HTML,CSS,SCSS
Close #281
Fixes contact us. I'll make  a separate PR for About Us if this design is approved
https://github.com/apu52/METAVERSE/assets/68018372/6cdfa1f0-4bcf-467d-9776-63cad5765ccb
Codepeak, KWOC

fixed contact us

---

Projects/Food_Ordering_Website/style.css

Title :Logo of the Food-ordering website.
Fixes #266
Issue No. : #266 
The box shadow of the navbar was missing after a recent PR by someone. Therefore besides adjusting the image dimensions i have also added the box shadow as it was in the earlier version.
Screenshot:

FIX:Logo of the Food-ordering website.

---

about old.html
about.css
about.html
assets/css/style.css

Title : Issue #288 
Issue No. :#288
Code Stack : HTML,CSS, Javascript
Close #288
https://github.com/apu52/METAVERSE/assets/68018372/c01e911c-fa7f-418e-9dae-2278cbc8a995
Codepeak, kwoc

About us redesigned

---

Projects/Detect Device Battery/index.html
Projects/Detect Device Battery/index.js

Title : Battery Time shown
Issue No. : #292 
Code Stack : Javascript, HTML
Close #292 
codepeak, kwoc

added changes to show time

---

Projects/Meme_Generator/index.html
Projects/Meme_Generator/style.css

Title :Fixed the UI and fonts of the Meme generator web app project.
Fixes #267 
Issue No. :#267

Fix:meme generator-UI

---

Projects/Scientific_Calculator/index.html

Fixes #299 
Title : Made Scientific calculator responsive
Issue No. : #299 
Screenshot:

Made Scientific calculator responsive

---

assets/css/style.css
index.html

Title: Realignment of Dark mode toggle button
Issue No. : #340 
Code Stack: HTML, CSS
Close #340 
- min-width : 375px 
- min-width: 768px 
The dark mode toggle button is re-positioned such that it does not overlap the home button in the mobile viewport.
***Are you contributing under any Open-source program?***
KWOC

re positioned the toggle button

---

Projects/Age_Calculator/style.css

#Modified the UI of the refresh button in Age Calculator
Fixes #349 
Title :Modified the UI of the refresh button in Age Calculator
Issue No. : #349
Screenshot:

Modified the UI of the refresh button in Age Calculator

---

Projects/Quote_Generator/index.html
Projects/Quote_Generator/script.js
Projects/Quote_Generator/style.css

Fixes #349 
Title : dark mode-toggler in Quote of the day web app
Issue No. :#349
Screenshot:

FEAT:dark mode-toggler in Quote of the day web app

---

Projects/Hackathons/contact.html
Projects/Hackathons/css/style.css

fixes #407 
Title : Improved UI and contact page of the Hackathon website.
Issue No. : #407 
Screenshot:

Improved UI and contact page of the Hackathon website.

---

Projects/Meme_Generator/style.css

#Made the Meme-generator web app responsive.
Fixes #406 
Title : Made the Meme-generator web app responsive.
Issue No. : #406
Screenshot:

Made the Meme-generator web app responsive.

---

Projects/MATH_SPRINT_APP/style.css

Fixes #443 
Title : Made the Maths-Sprint-app working in Desktops. by solving the overflow problem.
Issue No. : #443 
Screenshot:

Made the Maths-Sprint-app working in Desktops.

---

Projects/HOSTEL_MANAGEMENT/style.css

#Rectified the display of navbar in Hostel management website
Title :Rectified the display of navbar in Hostel management website
Issue No. : #555 
Now the navbar is visible properly  either in hamburger form or in normal form.

Rectified the display of navbar in Hostel management website

---

Projects/Github_Profile_Viewer/style.css

#Updated the UI of GITHUB-PROFILE-GENERATOR
Title :Updated the UI of GITHUB-PROFILE-GENERATOR
Fixes #585 
Issue No. : #585
Yes under KWOC

Updated the UI of GITHUB-PROFILE-GENERATOR

---

Projects/Temperature_Converter/style.css

#Made the Temperature Converter responsive
Fixes #597
Title : Made the Temperature Converter responsive
Issue No. : #597 

Made the Temperature Converter responsive

---

Projects/Health Dashboard/index.html
Projects/Health Dashboard/index.js

Title :Adding darkmode in health dashboard
Fixes #599 
Issue No. : #599 

Feat:adding darkmode in health dashboard

---

Projects/Guess_the_Number/style.css

Title :Made the Guess the number game responsive
Fixes #600 
Issue No. : #600 

Made the Guess the number game responsive

---

Projects/Health Dashboard/index.html

Title :Made the Health Dashboard dynamic
Issue No. : #606 
Close : #606 

Made the Health Dashboard dynamic

---

Projects/NFT_Website_Clone/style.css

Title : The Discover more button is fixed.
Issue No. : #609 

The Discover more button is fixed.

---

README.md

Title : Adding a Discord icon in the readme
Issue No. : #624
Code Stack : 
Close #<#624>
***Are you contributing under any Open-source program?***
GSSOC'24

Sibam paul patch 1

---

Projects/Food_Website/index.html

Title : Food Website styles and items are not loading
Issue No. : #631
Code Stack : html changes only
Close #631
2 Commits in total
- Prettier is applied to code for better readability in first commit
- Path is updated in second commit to load styles and index.js file to make website work

fix(631): load style and index.js correctly in food website

---

Projects/Book_review_website/index.html
Projects/Book_review_website/main.js
Projects/Book_review_website/signin.html
Projects/Book_review_website/signup.html

Title : Authentication system is made in Book review website.
Issue No. : #641
Code Stack : 
HTML ,CSS ,JS , and Firebase
Close #641
https://github.com/apu52/METAVERSE/assets/127030695/6b0eda14-9409-4fd7-90ab-da63407a0839
Yes under GSSOC'24

Book review authentication is complete.

---

Projects/Amazon-Clone/index.html
Projects/Amazon-Clone/style.css

Title : Enhancement in the UI of Amazon clone
Issue No. : #640
Code Stack:  HTML, CSS
Close <#640>
https://github.com/apu52/METAVERSE/assets/138794574/34d6caa5-bb82-4d26-b913-c5b529cb5ce4
- [X ] I have commented on my code, particularly in hard-to-understand areas
- [X ] I have gone through the  `contributing. md` file before contributing
I  added the hover effects to the cards and changed the navbar elements.
Made some changes regarding font size, and color.
Added the hover effect to the Amazon logo above the footer.
***Are you contributing under any Open-source program?***
Yes, I am a contributor at [gssoc`24.]

overall enhancement in the UI of Amazon clone

---

Projects/Book_review_website/style.css

Title :The menubar and the hero section is now properly visible in mobile devices
Issue No. : #645 
Close #645
Yes under GSSOC 24

The menubar and the hero section is now properly visible in mobile devices

---

Projects/Age_Calculator/index.html
Projects/Age_Calculator/style.css

Title : Made the Age Calculator Responsive
Issue No. : #654 
Code Stack : 
Close #654
Yes I am contributing in gssoc24

Made the age calculator responsive

---

Projects/AI_Image _Generator/index.html
Projects/AI_Image _Generator/script.js
Projects/AI_Image _Generator/signin.html
Projects/AI_Image _Generator/signup.html
Projects/AI_Image _Generator/style.css

Title :Backend of AI Image generator is complete
Issue No. : #660 
Close #660
https://github.com/apu52/METAVERSE/assets/127030695/fe34eadd-f5ee-4c93-a27b-48f1771b7719
I have added the Recent Search functionality using Local storage as well as added firebase authentication.
In the video a little bit of the left side screen is cropped thatswhy i provided a screenshot of the main page.
Yes under GSSOC

Backend of AI Image generator is complete

---

assets/css/style.css
contact.html

…in the Contact Us Page. #673
Title : Changed the padding and gap of the Contact page. gssoc Display Issue …gssoc  
Issue No. :  #673
Code Stack : HTML, CSS
Close #673
https://github.com/apu52/METAVERSE/assets/144688422/2ccccb76-21ca-41a5-8b89-539c6cec4353
I am contributing to GSSoC 2024

Changed the padding and gap of the Contact page. gssoc Display Issue …gssoc  #673

---

Projects/Quote_Generator/style.css

Title :Quote of the day is not responsive 
Issue No. :#663
Code Stack : 
Close #663 
After changes the quote of the day project mobile view.
Yes I am contributing it under GSSOC24

Made the quote of the day project responsive 

---

.github/workflows/closed-issue.yml
.github/workflows/issue-comment.yml

Title : Auto commenting on issues and self assign
Issue No. : #675 
Code Stack : 
Close #675 
GSSOC'24

Auto commenting on issues and self assign

---

Projects/Hackathons/contact.html

Title : updated contact page to the hackathons website
Issue No. : #651
Code Stack : 
1. Changed style of h1 in contact page
2. Added colour to form
3. Added new colour to buttons
4. Added hovering effects
5. Added content to footer
6. Added style to footer
7. Added responsive styles
8. Corrected the navbar
Close #651 
Close #651 as this PR will solve it
Before:
Now:
I am contributing under GSSoC 2024.. 
@apu52 Please assign me this PR and label this PR under GSSoC 2024

feat: updated contact page to the hackathons website #651

---

Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/readme.md
Projects/Food_Ordering_Website/style.css

Title : food ordering footer
Issue No. : #670 
Code Stack : 
1. **index.html**
- Redesigned the footer to display "Our Services", "Contact", "Locations", and "Follow Us On" in a single row.
- Added hover effects to the "Our Services" section to improve user interactivity.
- Included phone and email icons in the "Contact" section with hover effects.
- Enlarged the "Follow Us On" icons and added hover and pointer effects to enhance visibility and usability.
2. **style.css**
- Updated CSS to style the footer row, ensuring all sections are aligned horizontally.
- Implemented hover styles for the "Our Services" section to change appearance on mouse-over.
- Styled the phone and email icons in the "Contact" section, adding hover effects for better user feedback.
- Adjusted the size of the …

footer changed of the food ordering website

---

about.html
assets/css/about.css
assets/css/style.css

Title :In light mode the headings are not clearlt visible #680
Issue No. : #680 
Code Stack : 
Close #680
yes I am contributing under gssoc24

fixed the text visibility of headings and other texts

---

Projects/Food_Ordering_Website/index.html

Title : add Food website logo
Issue No. : #696
Code Stack : HTML,css
Close #696
Uploading icon added.mp4…
please add level 
Thank you for allowing me to contribute to your project. ❤️. 
***Are you contributing under any Open-source program?***
gssoc

added logo

---

Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/index.js
Projects/Food_Ordering_Website/style.css

Title : Added back to top icon to food ordering website 
Issue No. : #712 
Code Stack : HTML, CSS and JavaScript
Closes #712 
1. Added back to top icon to html file
2. Added styles to back to top icon
3. Made the back to top icon functional using javascript
@apu52 I am contributing under GSSoC 2024.. Please label this PR under GSSoC

Added back to top icon to food ordering website #712

---

Projects/AI_Image _Generator/index.html
Projects/AI_Image _Generator/script.js
Projects/AI_Image _Generator/style.css

Title :Added Toggle functionality in AI Image generator as well as kept it responsive
Issue No. : #682 
Close #682 
https://github.com/apu52/METAVERSE/assets/127030695/540a145a-6a8a-4c21-9c44-3cb5a9710548
Yes under GSSOC

Added Toggle functionality in AI Image generator

---

contact.html

Title : [Feature Request]: ADD The PROJECT MAINTAINERS in the CONTACT US PAGE
Issue No. : #716 
Code Stack : HTML
Close #716 
https://github.com/apu52/METAVERSE/assets/122982506/4fa4cc37-cda3-4d25-98c7-a9eb8682036d
Added 3 project maintainers details in contact us page So contributors will also be able to have a good idea about the repo
GSSOC-24
If you have any further feedback or require any modifications, please feel free to share. I appreciate your attention to detail

Added maintainers information in contect us page

---

assets/css/style.css
index.html

Title : The mouse cursor on mobile
Issue No. : 706
Code Stack : html, css
Close #706 
video showing cursor on desktop, tablet and mobile.
https://github.com/apu52/METAVERSE/assets/32983571/5c869561-1475-4b4e-b860-f1257ec157be
gssoc 24'

removed cursor on mobile and tablet screens

---

Projects/Travel_Website/styles.css

1. Add a transitions on hovering to the destination card 
2. Add a transitions on hovering to the trip card 
3. Added scaling hover effect to image in gallery_col 
4. Added focus effect to input in subscribe form 
5. Added transition to p in footer
Title : Added Styles and hovering effect and animations to the travel website  
Issue No. : #726
Code Stack :  HTML, CSS, JavaScript
Close #726
@apu52 I am contributing under GSSoC 2024

Added Styles and hovering effect and animations to the travel website  #726

---

assets/js/script.js

Title : Consistent Theme toggle state across different pages
Issue No. : #745 
Code Stack : HTML , CSS , JS
Close #745 
https://github.com/apu52/METAVERSE/assets/68507333/b52376b8-b322-4450-a801-a4fc61fb24bd
GSSOC

added function to retain the theme across pages

---

.github/workflows/greetings.yml

Added github bot
Title :Automate greeting using Github bot 
Issue No. : #746 
Code Stack : 
Close #746 
https://github.com/apu52/METAVERSE/assets/68507333/47edca8d-3abf-4e3d-8f11-aeb11c3200eb
Also Make sure to allow Read and write permission (under Setting -> Actions -> General -> Allowing Read n write Permission)
GSSOC

Added the Automate BOT

---

Projects/organica/assets/css/home.css

Issue No. : #742 
Code Stack :  HTML, CSS, JavaScript
Close #742 
1. Added heroSubtitleAnimation
2. Added heroTitleAnimation
3. Added heroTextAnimation
4. Added heroButtonAnimation
5. Added servicelconAnimation
6. Added serviceTitleAnimation
7. Added offersCardAnimation
8. Added offersSubtitleAnimation
9. Added offersTitleAnimation  
10.Added offersButtonAnimation
11. Added animations to Cta section
12. Added animations to top card section
13. Added partnerLogoAnimation
14. Added animations to testimonials section
15. Added animations to blog cards section
16. Added animations to newsletter section
17. Added all animation functions
@apu52 I am contributing GSSoC 2024

 Added Styles and hovering effect and animations to the organica website

---

Projects/Career-Crafters/app.js
Projects/Career-Crafters/index.html
Projects/Chat_App/src/styles/style.css

Title :Adding a back button for the sidebar and more and adding more info for the detail section in the company section 
Issue No. : #744
Code Stack : HTNL, CSS, JS
Close #744
This is the website before changes
https://github.com/apu52/METAVERSE/assets/144688422/5733cfab-b708-447b-853d-0dfd86244906
This is the website after changes to the website
https://github.com/apu52/METAVERSE/assets/144688422/d91000b4-4fc3-4dc9-8f7a-753a422e1396
I am contributing under GSSoC 2024.

Adding a back button for the sidebar and more 

---

Projects/JokesApp/index.html
Projects/JokesApp/style.css
Projects/JokesApp/yourjoke.html

Title : Created the add your own joke functionality
Issue No. : #731 
I have used Local storage to save the jokes and display one joke randomly from the list using vanilla JS. The website is also responsive and i have kept the original styling of it.
Close #731 
https://github.com/apu52/METAVERSE/assets/127030695/613d4673-b231-4b4a-a370-262c7d34e77d
Yes under GSSOC 24

Created the add your own joke functionality

---

Projects/Wildvine/assets/css/style.css
Projects/Wildvine/index.html

Title : Add Follow Us section in Wildvine webpage
Issue No. : #758 
Code Stack : 
Close #758 
I am contributing under GSSoC'24

Adding Social Media section in footer

---

Projects/IT_Solution/assets/css/style.css
Projects/IT_Solution/assets/js/script.js
Projects/IT_Solution/index.html

Close #763 
https://github.com/apu52/METAVERSE/assets/127030695/f12a9bdd-c557-48da-82aa-670f66ed3f48
Contributing under GSSOC.

Added Light and Dark mode feature as well as remembers the user's preferred mode

---

.gitignore
Projects/Myntra_Clone_Website/index.html
Projects/Myntra_Clone_Website/login.html
Projects/Myntra_Clone_Website/package-lock.json
Projects/Myntra_Clone_Website/package.json
Projects/Myntra_Clone_Website/server.js
Projects/Myntra_Clone_Website/signup.html

Title :Adding Login and Signup page in Myntra Clone
Issue No. :  #697
Code Stack : HTML, CSS, JavaScript, NodeJs, ExpressJs, MongoDB
Close #697 
https://github.com/apu52/METAVERSE/assets/123234748/486a29b6-9981-4611-a9a0-974fde8bc27e

Added Login and Signup page 

---

Projects/WakemeUp/index.html
Projects/WakemeUp/style.css

Update in the UI so it follows a color pallette
Title :
Issue No. : #783 
Code Stack : HTML, CSS, JavaScript
Close #783 
https://github.com/apu52/METAVERSE/assets/130339327/67718069-a4b9-4c30-bd76-752d61dffc7b

Changed the UI so it follows a color scheme

---

Projects/Blog_Website/index.html
Projects/Blog_Website/post.html
Projects/Blog_Website/style.css

Issue No. : #759
Code Stack :  HTML, CSS, JavaScript
Close #759
1. Added Light gray background
2. Added styles to the header
3. Added box shadow for Header
4. added color to icons
5. Added transition
6. Added colors on hovering
7. Added position to the background overlay
8. Added a good background overlay to the hero section
9. Added hovering effect on transition to the hl of hero content and text shadow and changed the color
10. Added hovering effect for hl in hero content
11. Added text color to the hut of hero content and add a text shadow and transition effect on hovering
12. Added hovering effects
13. Added a smooth transition function for image transform in hero image
14. Make the image slightly larger on hover
15. Added styles to buttons
16. Add an hovering effect on box shadow on …

Added styles hovering effect and transitions to blog website

---

about.html
assets/css/style.css

Title : about page style improved
Issue No. : 778 
Code Stack : Html, Css
Close #778
Its not a project just improvement

about page style improved

---

README.md

Title : [Documentation Update]: Documantation for docker
Issue No. : #797 
Code Stack : Markdown 
Close : #797

added documentation for docker

---

Projects/Calendar/index.html
Projects/Calendar/script.js
Projects/Calendar/style.css

Title :Added the ability to select a specific year and month in the calendar
Issue No. :#799
Code Stack : HTML, CSS, JavaScript
Close #799
After Changes:
https://github.com/apu52/METAVERSE/assets/117555508/0a56c6f4-a32f-4a09-af99-54dc3041eae1
Code Changes:
https://github.com/apu52/METAVERSE/assets/117555508/06f9e71f-1add-4566-a022-33ba8a2b7cfb

Drop Down Feature Added

---

Projects/To-Do_List_Project/index.html
Projects/To-Do_List_Project/styles.css

Title : To do list is not responsive
Issue No. : #743 
Code Stack :  HTML ,CSS
Close #743 

Made todo list responsive

---

.vscode/settings.json
about.html
assets/js/script.js
contact.html
index.html
style.css

Hello @apu52 
Title : Hover effect on the navbar
Sincere apologies but earlier pull request was accidentally closed. PR Merged #819 
Issue No. : #772
Code Stack : HTML, CSS, JAVASCRIPT
Close #772
Also, I'll be highly obliged if you could add difficulty level to the issue #772.
ASKED CHANGES--
https://github.com/apu52/METAVERSE/assets/129287425/995015a1-3650-41cd-aa8e-c486be157b55
https://github.com/apu52/METAVERSE/assets/129287425/0ccfa35c-9305-4413-96ff-f9e6b8296e1e

Hover effect on navbar + suggested changes included

---

Projects/LogIn_Page/forgot.html
Projects/LogIn_Page/index.html
Projects/LogIn_Page/styles.css

Title :Request Forgot password form
Issue No. : fixes #693 
[3814a159-9b82-421b-a8be-34ada089957a.webm](https://github.com/apu52/METAVERSE/assets/140897461/015c46f2-8d26-431a-a278-668ef23a89b1)

Forgot password

---

about.html
assets/css/style.css

#794 
Title :Text aligned on About page
Issue No. : #794
Code Stack : 
Close #794
- [ x] I have commented my code, particularly in hard-to-understand areas

about page text center

---

.github/workflows/autocomment-pr-raise.yml
.github/workflows/greetings.yml

Title: Implement Automatic Comment Functionality on Pull Request Creation
Issue No.: 781
Code Stack: YML
Close #781

Implement Automatic Comment Functionality on Pull Request Creation

---

Projects/Digital_Clock/style.css

Title :Digital clock is not responsive
Issue No. : #825 
Code Stack : CSS
Close #825 

Made the clock responsive

---

Projects/Password-Strength/index.html
Projects/Password-Strength/script.js
Projects/Password-Strength/style.css

Password-strength
Title : password-strength-checker
Issue No. : #853 
Code Stack : html-css-js
Close #853 

[Feature Request]: password strength checker has no files #853

---

Projects/Travel_Website/index.html
Projects/Travel_Website/styles.css

Title : Adding follow us section in travel website footer
Issue No. : #821
Close #821

Added follow us section in footer

---

index.html

Title : Result not found removed
Issue No. : #857 
Code Stack : 
HTML
Close #857
https://github.com/apu52/METAVERSE/assets/130382676/a65ce3fc-4b9a-49ee-88c9-0f6c38ad18b4
The result not found part was showing even when the user has not searched for anything. I have fixed the code so that it only appears when the user has searched for a project and the project is not available. 

Result not found removed

---

Projects/Lyric_Finder/index.html

Hello @apu52 @anuragverma108 @heysagnik 
Title : Logo directing to home page not working in LYRIC FINDER
Issue No. : #864 
Code Stack :  HTML CSS JS
Close #864 
Please assign this under GSSOC and the difficulty label as well!
EARLIER--
NOW--
https://github.com/apu52/METAVERSE/assets/129287425/d67e9bd6-e224-4ecb-9477-a7608e331288

Update index.html path to homepage

---

Projects/Detect Device Battery/index.js

Hello @apu52 @anuragverma108 @heysagnik 
Title : Detect battery project not working
Issue No. : #899 
Code Stack :  HTML CSS JAVASCRIPT
Please assign this under GSSOC and the difficulty label as well!
Close #899 
Now it shows the device is charging too!!

detect_battery%_corrected

---

contact.html

Issue number : 868
Title : Shruti and Ankita image not displaying fixed
Issue No. : #868
Code Stack : HTML CSS JAVASCRIPT
Close #868 
Please assign this under GSSOC and the difficulty label as well!

Shruti and Ankita image not displaying fixed

---

Projects/Myntra_Clone_Website/about.html
Projects/Myntra_Clone_Website/blog.html
Projects/Myntra_Clone_Website/index.html
Projects/Myntra_Clone_Website/login.html
Projects/Myntra_Clone_Website/shop.html
Projects/Myntra_Clone_Website/signup.html

Title : Myntra Clone 404 error
Issue No. : 894
Code Stack : 
Close #894 

Removed 404 error in myntra clone

---

Projects/Hulu_clone/index.html
Projects/Hulu_clone/style.css

Title :[UI Enhancement]: Adding a hover effect to the show cards on Hulu Clone Website #891 
Issue No. : #891 
Code Stack : HTML,CSS, JavaScript
Close #891 
The button for get started changes background colour when hovered, the show cards and sports logo get scaled in size when hovered and I added colour to the footer links to change to green when hovered.
Before:
After Hover:

Added hover effect to the show cards, sport logos, buttons and footer links on Hulu Clone Website 

---

Projects/Hotsar_Clone/Index.html

Hello @apu52 @anuragverma108 @heysagnik 
Title : HOTSTAR_CLONE 404
Issue No. : #897 
Code Stack : html css JAVASCRIPT
Please assign this under GSSOC and the difficulty label as well!
Close #897 
https://github.com/apu52/METAVERSE/assets/129287425/c801a86a-64e9-4a14-a672-2e9da64f86fc

error-404_solved

---

Projects/Amazon-Clone/style.css

Hello @apu52  @anuragverma108  @heysagnik 
Title : Responsiveness not appropriate 
Issue No. : #887
Code Stack :  Html css JS
Please assign under gssoc and the appropriate difficulty level.
Close #887 
earlier--
now--
https://github.com/apu52/METAVERSE/assets/129287425/2144f90f-afff-4adf-b90d-5cb499df9965

responsiveness-improved of Amazon clone

---

about.html
assets/css/style.css
index.html

Title : Added hover with proper color on social icon in footer
Issue No. : #910 
Close #910 
Before :
After:
https://github.com/apu52/METAVERSE/assets/162733812/970c7046-f0db-4b31-b0ca-34085190f61b
- I added hover effect on social icons in footer , on hovering they will change to their respective logo colors and will scale up
- Also , I  fixed the width of footer on home page , it doesnt cover full width and hence doesnt look good , also their are no social icons in footer of home page , I added them like they are in about us section

Added hover on social icon

---

Projects/Video-player/index.html
Projects/Video-player/script.js
Projects/Video-player/style.css

These changes make the video player easier to use and nicer to look at. The layout is clearer, the buttons and progress bar are more stylish, and the video controls work smoothly. It's designed to give you a better experience when watching videos online, with everything working just as you'd expect
Title :Improving ui for video player
Issue No. :#830
Code Stack : html css js
Close #830 
https://github.com/apu52/METAVERSE/assets/137192044/279daa7c-8f37-452e-9c32-0e9eda56637f

changes done

---

Projects/Brick_Breaker_Game/script.js

Title :Brick_Breaker_Project  made ball bounce back from top wall
Issue No. :#815
Code Stack : js
https://github.com/apu52/METAVERSE/assets/155251909/eed16bfb-dbb0-43cd-bc1d-b7adf648e983
Close #815

made ball bounce back when it hits top wall

---

Projects/Recipe-App/index.html
Projects/Recipe-App/script.js

Title : Recipe is not getting fetched in recipe app
Issue No. : #922 
Code Stack : 
Close #922 
I have rendered the initial 21 recipes on the main page: 
The search bar also works fine now

Recipes app bug: Recipes fetch resolved

---

Projects/Quiz_App/index.html
Projects/Quiz_App/script.js
Projects/Quiz_App/style.css

**Added keyboard shortcuts to help you navigate:  1, 2, 3, 4: Select the respective answer. Enter: Proceed to the next question or close this message.**
Issue No. : #867 
Code Stack : 
HTML 
CSS ,
Javascript
Close #867 
https://github.com/apu52/METAVERSE/assets/132948936/22aa0beb-799e-450e-a0f5-e453362e5158

22.Quiz , Added keyboard shortcuts .

---

Projects/Myntra_Clone_Website/style.css

Title : Adding Styles and hovering effect and animations to the Myntra clone Website 
Issue No. : #789
Code Stack :  HTML, CSS, JS
Close #789 
1. Added styles to the header
2. Add transition effect to header box shadow
3. Enhanced hover shadow for header 
4. Add transition for color change and scaling on hover
5. Scale up on hover
6. Add transition effect to navbar
7. Add transition for smooth movement
8. Add hover effect to navbar link
9. Add transition for color change
10.  Added styles to hero section
11. Add background position transition
12. Shift background on hover
13. Add transform and box shadow transitions
14. Scale up on hover
15. Add hover box shadow
16. Add transition for color change and scaling on hover
17. Scale up on hover
18. Added styles to feature section
19.  Added …

Added Styles and hovering effect and animations to the Myntra clone Website #789

---

Projects/cyberWise/index.html
Projects/cyberWise/style.css

Title : Update the UI of CyberWise Website 
Issue No. :#900 
Code Stack : 
Bootstrap, HTML, CSS, Javascript
Close #900 
https://github.com/apu52/METAVERSE/assets/130339327/84aae338-02c0-4e57-aa13-abec3942ad64

CyberWise Website UI Updated

---

about.html
assets/css/style.css
contact.html
copyright.html
index.html
privacynotice.html

Title :  New pages for privacy notice and copyright policy
Issue No. : #950 
Closes #950 
https://github.com/apu52/METAVERSE/assets/162733812/b0d61bb8-5166-4364-9062-8c6421ad9151
I have added links to copyright policy and privacy notice in footer of all pages.

Doc : Made new pages for privacy notice and copyright policy

---

deployment-app.yml
package-lock.json
service-app.yml

Title :kubernetes for app container
Issue No. : #835 
Code Stack : yaml file
Close #835 
https://github.com/apu52/METAVERSE/assets/97390553/3b823ac2-379c-48a0-96a5-2e09fffc0b0c

add kubernetes file

---

.vscode/settings.json
Projects/Travel_Website/index.html
Projects/Travel_Website/styles.css

Title : Back to top button added on the Travel Website
Issue No. :936
Code Stack : 
Close #936
**Before:**
**After:**
**Back to top button is added and it is visible in the bottom right corner in blue color**

Back to top button added on the Travel Website

---

Projects/Food_Ordering_Website/style.css

Title :Hover effects added to food website
Issue No. : #962 
Code Stack : CSS
Close #962

Hover effects added

---

about.html
contact.html
index.html

Title : remove extra elements and toggle .
Issue No. : fixes #970 
Code Stack : html
Close #970 
https://github.com/user-attachments/assets/01747496-a547-4600-b172-ae93e506e74c

remove extra elements and toggle

---

assets/js/contact.js
contact.html
style.css

Title : Add Contact Us Form 
Issue No. : 976
Code Stack : html , css ,js
Close #976 
https://github.com/user-attachments/assets/b01aa651-2e05-439e-ad1b-5d33d178f0a5

add contact us form 

---

Projects/Bake_website/index.html
Projects/Bake_website/menu.css
Projects/Bake_website/menu.html

Title : **Add Menu Items in Bakery Website**
Issue No. : #983 
Code Stack : html css
Close #983
https://github.com/user-attachments/assets/6338c8fa-6844-4a92-bd3d-b45ad01b6822

add menu items in bakery website

---

Projects/Netflix_clone_Project/index.css
Projects/Netflix_clone_Project/index.html

#981 
Title : "Frequently Asked Questions" section in Netflix Clone
Issue No. : #981 
Code Stack :  FAQ section made functional !
Close #981 
https://github.com/user-attachments/assets/9d28765d-1ea9-4234-8367-5a4c130478e9

FAQ section

---

Projects/TIC_TAC_TOE/script.js

Title : Fixed bugs in TicTacToe Game
Issue No. : 977
Code Stack : JS
Close #977 

Fixed bugs in TicTacToe Game

---

Projects/barber/assets/css/style.css
Projects/barber/index.html

Title : add contact section for barber website
Issue No. : #989
Code Stack : html css
Close #989

add contact section for barber website

---

Projects/Amazon-Clone/index.html
Projects/Amazon-Clone/style.css

Title :add some items in footer near logo 
Issue No. : 990
Code Stack : html css
Close #990
BEFORE : 
AFTER : 

add some tools in footer in amazone clone website

---

Projects/Myntra_Clone_Website/login.css
Projects/Myntra_Clone_Website/login.html
Projects/Myntra_Clone_Website/style.css

Title : Enhanced login page of Myntra
Issue No. : 988
Code Stack : HTML , CSS 
Close #988 
Before ;
After;

Enhanced Myntra clone login page

---

index.html
scrolldownprogressbar.js
style.css

Title : Scroll down progress bar added
Issue No. : #964 
Code Stack : HTML,CSS,JS
Close #964 
https://github.com/user-attachments/assets/1b07af8f-3240-4bd8-8a54-851cc0d56610

scroll down progress bar added

---

Projects/Hackathons/css/style.css
Projects/Hackathons/index.html

Title : Footer
Issue No. : 987
Close #987 
Before:
https://github.com/user-attachments/assets/b890e18d-52cf-4677-b038-1910785843c7
After :
https://github.com/user-attachments/assets/43d26cfd-65ed-497f-83e4-729584ad28fc
I have made a footer for the hackathon's website which gives it a complete look

Added footer in hackathons' website

---

README.md

Title : Documentation Update Correct Markdown Usage in Readme.md
Issue No. : 991
Code Stack : HTML, Markdown
Close #991

Markdown updated

---

Projects/Farmers-WebApp/static/info2.css
Projects/Farmers-WebApp/static/main1.css

Title :Content overflow is fixed
Issue No. : #1002 
Code Stack : CSS
Close #1002
https://github.com/user-attachments/assets/a753a262-856c-44db-9a1a-fc2e9c8756fa

content overflow fixed

---

Projects/Food_Ordering_Website/cart.html
Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/index.js
Projects/Food_Ordering_Website/style.css

Title : Adding the cart page in food ordering website
Issue No. : #944 
Code Stack : 
Close #944 
Alert while adding item to cart
The cart page - with quantity adjustment function, dynamically changing item price
Items can be removed from the cart
Please look at the amount of changes i have made and give the level 2 or 3 label.  

Added the add to cart feature in food ordering website

---

Projects/Food_Ordering_Website/style.css

Title : Floating Aninmation Added
Issue No. : #1007 
Code Stack : 
Close #<issue_no> #1007 
https://github.com/user-attachments/assets/cf44b637-6395-41b4-b790-df793c171a17

Floating Aninmation Added

---

Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/style.css

Title :
Issue No. : #1008 
Code Stack : 
Close #1008

Newsletter Section Added

---

Projects/Tindog_website/index.html
Projects/Tindog_website/style.css

Title : make contact us for tindog website and adding a popup thanks for subscribing when someone subscribe the website 
Issue No. : #1012 
Code Stack : html css and js
Close #1012 
popup on subscribing :  
https://github.com/user-attachments/assets/757642df-9cf2-48cc-b4d5-bde8b564ed10

make contact us for tindog website and adding a popup thanks for subscribing when someone subscribe the website 

---

style.css

Hey @apu52 
- issue closes #1016 
I have made the Contact Us page responsive

Made The Contact Us Page "Responsive"

---

Projects/Book_review_website/index.html

Title : Popup on subscribing newletter
Issue No. : 1022
Code Stack : HTML,CSS,JS
Closes #1022 
https://github.com/user-attachments/assets/e7de7ef6-70cb-4287-a310-1e68db9d325c

Added popup on subscribing to newsletter in "book review website"

---

Projects/HOSTEL_MANAGEMENT/index.html
Projects/HOSTEL_MANAGEMENT/style.css
Projects/Tindog_website/style.css

Title : add hover on social icon of hostel management
Issue No. : #1014 
Code Stack : 
Close #1014 
https://github.com/user-attachments/assets/3705dd9b-f51a-425f-9a12-5bcc2d851b61

feat: add hover on social icon of hostel management

---

Projects/Notes_App/style.css

Title :  Content overflow of in Notes App fixed.
Issue No. : 1046
Code Stack : HTML, CSS
Close #1046 
https://github.com/user-attachments/assets/7afb5651-5cc5-4b8d-b6a5-2c529c56b2b6

Fixed overflow of content in Notes App

---

Projects/Restaurant_Website/index.html
Projects/Restaurant_Website/style.css

Title :
Issue No. : 1031 
Code Stack : 
HTML, CSS, JAVASCRIPT
Fixed #1031 

Navbar in Restaurant Website is added

---

README.md

Title : [Documentation Update]: Inconsistent Color Scheme and Typography
Issue No. : 994
Code Stack : HTML, CSS, JS
Close # 994

Inconsistent Typography & Markdown edited

---

README.md

Title : [Documentation Update]: Lack of Detailed Setup Instructions
Issue No. :
Code Stack : 993
Close #993

Setup Instructions added

---

Projects/Hotsar_Clone/index.html

Title : Images not visible in Hotstar clone
Issue No. : #1047 
Code Stack : 
Close #1047 

The images visible in Hotstar Clone

---

Projects/Furniture-website/assets/css/style.css
Projects/Furniture-website/index.html

Title : add footer in furniture website
Issue No. : #1044
Code Stack :  html js and css
Close #1044 

add footer in furniture website

---

Projects/Restaurant_Website/index.html

Title :
Issue No. : #1010
Code Stack :  HTML,CSS
Close #1010 

Newsletter Button

---

Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/style.css
Projects/Restaurant_Website/index.html

Title :
Issue No. : #1009 
Close #1009

Cards hover enhacement

---

Projects/LogIn_Page/signup.html

Title : Signup form
Issue No. :1051
Code Stack : HTML,CSS , JS
Close #1051 
- I have also added an alert if password and confirm password dont match

Added signup form in "login page" project

---

about.html
contact.html
copyright.html
index.html
privacynotice.html

Hey @apu52 
- issue closes #1074 
I have hidden the cursor trail effect in the mobile view
https://github.com/user-attachments/assets/762bf672-a5a4-41a9-8f9b-cddb802420cf

Hide the Cursor Trail Effect in Mobile View

---

about.html
contact.html
contributor.html
scrolldownprogressbar.js
style.css

Hey @apu52 
- Issue fixes #1069
- I have fixed the working of scroll down progress bar 
- Additionally I have added the bar in all missing pages to maintain consistency across the website
- About us
- Contact
- Contibutor
https://github.com/user-attachments/assets/98c3a0df-bbb0-4adf-997a-0a0b60b03826

Fix and Added the "Scroll Down Progress Bar"

---

Projects/Marketing_agency/assets/css/style.css
Projects/Marketing_agency/index.html

Title : add footer of marketing agency website
Issue No. : #1067 
Code Stack : html css js
Close #1067 

add footer of marketing agency website or inno hub website

---

Projects/Hotsar_Clone/index.html
Projects/Hotsar_Clone/login.css
Projects/Hotsar_Clone/login.html

Title : Adding login page in "Hotstar Clone" project
Issue No. : #1083
Close #1083 

Added login page in hotstar clone

---

Projects/Bootstrap_clone/index.html
Projects/Bootstrap_clone/style.css

Title : Addition of navbar same as original and added a feature for copied to clipboard 
Issue No. : #1103 
Code Stack :  Html , CSS and JS 
Close #1103 
https://github.com/user-attachments/assets/5720df04-d74d-42db-9e7f-4ac920edafeb

Added Navbar as same as Original Bootstrap and added a feature to copied to clipboard for the given text as bootstrap 

---

Projects/Scientific_Calculator/index.html

Title : Add more functions to the Scientific Calculator #1078
Issue No. : 1078
Code Stack : HTML, JS
Close #1078 

added many other functions in scientific calculator

---

Projects/Restaurant_Website/index.html
Projects/Restaurant_Website/style.css

Title :there is no title name in navbar of restaurants website
Issue No. :#1077
Code Stack : 
Close #1077

added title

---

Projects/eduland/assets/css/style.css
Projects/eduland/assets/js/script.js
Projects/eduland/index.html

Title : Add faq section and hover on social icons
Issue No. : #1100
Code Stack : html css and js 
Close #1100
https://github.com/user-attachments/assets/0922e0be-7365-4475-918f-bd2492cb4ae4

feat: add faq ssection and hover on social icons

---

Projects/IT_Solution/assets/css/style.css
Projects/IT_Solution/assets/js/script.js
Projects/IT_Solution/index.html

Title :  add faq section and hover on social icons
Issue No. : #1099
Code Stack : html css and js
Close #1099
https://github.com/user-attachments/assets/ecb514f4-2a42-469d-b432-79849fe8ca78

feat: add faq section and hover on social icons

---

Projects/Book_review_website/index.html

Title :Logo Changed to book review system
Issue No. : #1129 
Close #1129

logo changed

---

Projects/NewsApp/index.html
Projects/NewsApp/index.js
Projects/NewsApp/style.css

Title : Addition of search and hover functionality 
Issue No. : #1127 
Code Stack : Html , css and javascript
Close #1127
Sir if you find it suitable for lvl 2 please give 
https://github.com/user-attachments/assets/ed9fea75-d0c9-432f-8dbb-3a2c0637b903

Added search and hover functionality for the news app 

---

Projects/Gamex/assets/css/style.css
Projects/Gamex/assets/js/script.js
Projects/Gamex/index.html

Title : add contact us section
Issue No. : #1140
Code Stack : 
Close #1140
https://github.com/user-attachments/assets/2cbd48e3-f857-4838-a9ee-abdde1f36e62

feat: add contact us section

---

Projects/Marketing_agency/assets/css/style.css
Projects/Marketing_agency/assets/js/script.js
Projects/Marketing_agency/index.html

Title : add faq section
Issue No. : #1141 
Code Stack : html css and js 
Close #1141 
https://github.com/user-attachments/assets/b7a5f919-0b05-4cc1-8ded-778c57d68f38

feat: add faq section

---

Projects/Pet_Website/assets/css/style.css
Projects/Pet_Website/index.html

Title : Contact us in kitter - pet website
Issue No. : 1093
Close #1093 
https://github.com/user-attachments/assets/1c45c0da-cf61-42b3-92d0-dd045088ad27

Added contact us section in kitter - pet website

---

Projects/Gamics/assets/css/style.css
Projects/Gamics/index.html

Title : Added contact form
Issue No. : 1094
Close #1094 

added contact form in gamics project

---

Projects/Book_review_website/index.html

Title : Replace twitter with X
Issue No. : #1081 
Close #1081 

Added new twitter icon

---

Projects/Lyric_Finder/Readme.md
Projects/Lyric_Finder/index.html
Projects/Lyric_Finder/script.js
Projects/Lyric_Finder/style.css

Title :Lyrics app not working 
Issue No. : #851 
Code Stack : Updated the script.js , css file along with Readme.md
Close #851
Before
Updated 
Previously Get lyrics was not working in which it has been fixed here
- [] I'm a SSOC'24 contributor

lyrics functionality

---

Projects/Food_Ordering_Website/index.html
Projects/Food_Ordering_Website/style.css

Title : Enhance Our Menu Cards
Issue No. : #1166
Close #1166
Code Stack : HTML, CSS
#Image
- I'm a SSOC'24 contributor

enhance our menu section

---

index.html
style.css

Title : made Nav Bar Responsive for mobile Displays Also
Issue No. :#1144 
Code Stack : HTML , CSS , JS
Close #1144 

Made Nav Bar Responsive for mobile view also

---

Projects/Book_review_website/public/signin.html

Title : SignUP page is not linked with signup button in Book Review Website
Issue No. :#1107
Close #1107 

Added sign up page

---

Projects/Simon_Game/game.js
Projects/Simon_Game/index.html

Title :
Added functionality to the existing Simon Game.
Issue No. : #1187
Code Stack : HTML, CSS, JAVASCRIPT
Close #1187
Sir I request u to kindly add the favicon files from which the editing of the CSS content has been done as this project is open source,, favicon files such as favicon.io have been used by someone either to display font, or image or color. I request u to look into it. The rest code as been modified by me.

Added functionality to the existing Simon Game.

---

Projects/Rock-Paper-Scissors/index.html
Projects/Rock-Paper-Scissors/index.js
Projects/Rock-Paper-Scissors/style.css

Title : To display tie score as well along with user score and computer score in rock-paper-scissors game . 
Issue No. : #1180
Code Stack : HTML,CSS,JavaScript
Close #1180
https://github.com/user-attachments/assets/2e75d59d-3f06-430a-8ea1-3e8349107a8a

feat: Number of ties are now displayed along with wins and loses .

---

index.html

I Added Icons to Navbar 
Issue No. : #1168 
Code Stack :Html,css
Close #1168 
Kindly go through this PR @apu52 
https://github.com/user-attachments/assets/dfcb8d28-da44-46f6-82ba-3add6620e8bf

Added Icons to Navbar

---

Projects/Sudoku/index.html
Projects/Sudoku/script.js
Projects/Sudoku/styles.css

Title : Working Sudoku
Issue No. : #1149 
Code Stack : Html , css and jvascript
Close #1149 
https://github.com/user-attachments/assets/e135942e-c2d2-4107-8c82-8fb1b3508f72

Created working sudoku

---

Projects/eduland/assets/css/style.css
Projects/eduland/index.html

Title :contact section for eduland website
Issue No. : #1154
Code Stack : html css
Close  #1154
https://github.com/user-attachments/assets/81cac4a9-5944-4b86-8f85-ef6293cff4ae

feat: contact section for eduland website

---

Projects/Pet_Website/assets/css/style.css
Projects/Pet_Website/assets/js/script.js
Projects/Pet_Website/index.html

Title : add faq seciton for kitter website
Issue No. : #1174
Code Stack : html css and js 
Close #1174
https://github.com/user-attachments/assets/f0bff81c-c413-4a2f-8f3d-968cde6f569f

feat: add faq seciton for kitter website

---

Projects/Wildvine/assets/css/style.css
Projects/Wildvine/assets/js/script.js
Projects/Wildvine/index.html

Title :  add contact section in wildvine website
Issue No. : #1204
Code Stack : HTML CSS AND JS 
Close #1204
https://github.com/user-attachments/assets/4e12b7a3-3fc8-432d-89b6-7165d1e9b22d

feat: add contact section in wildvine website

---

Projects/Digital_Clock/index.html
Projects/Digital_Clock/script.js
Projects/Digital_Clock/style.css

Title : Display day and date along with time in Digital Clock .
Issue No. : #1202
Code Stack : HTML,CSS,JavaScript
Close #1202

feat: Day and Date are now displayed in the Digital Clock .

---

RateUs.html
about.html
contact.html
contributor.html
index.html

Hello Project Admin 
I Added Icons to all Pages - Solved #1213 
Kindly go through this PR @apu52 
Close #1213
https://github.com/user-attachments/assets/e7cf1ae6-b52d-4481-addb-055191394210

Added Icons to all Pages

---

about old.html
about.html
contact.html
contributor.html
copyright.html
index.html
privacynotice.html

Hey @apu52 
- issue closes #1212 
I have added the preloader to the all pages
- Created a pre-loader 
- Added percentage indicator
- Matched to the website design them
https://github.com/user-attachments/assets/c0f21038-0771-4f58-9597-6bd6b13f6bc2

Added Preloader to The Website

---

about.html

Title : Fixed about page for smalller screen sizes
Issue No. : #1220 
Code Stack : HTML CSS
Close #1220 

Fixed the about page for mobile screen size

---

assets/js/index.js
index.html

Title : None of the projects are visible on homepage
Issue No. : #1215 
Code Stack : 
Close #1215
The projects are visible locally but not on the hosted site. I have changed the code a bit according to error received on the hosted site and also added debug console logs. 

Projects getting displayed on homescreen

---

about.html
contact.html
contributor.html
index.html
style.css

Title : Navbar for Mobile screen
Issue No. : #1219 
Code Stack : 
Close #1219 
https://github.com/user-attachments/assets/92d08f3f-5a59-4c24-9f76-daa03a6d29ac

Added toggle navbar for mobile screen

---

Projects/Password-Strength/index.html
Projects/Password-Strength/script.js
Projects/Password-Strength/style.css

Title : Reset Button in Password Strength
Issue No. : Fixed #1130 
Code Stack : HTML, CSS, JS

Reset Button in Password Strength is added

---

assets/css/style.css
index.html

Title :  Add Newsletter Subscription Option to Footer
Please review this changes and approve
Issue No. : https://github.com/apu52/METAVERSE/issues/1052
Code Stack : 
Close #1052
not able to attach video
**Before** 
**After**

 Add Newsletter Subscription Option to Footer

---

assets/js/contact.js
backend/package-lock.json
backend/package.json
backend/server.js
contact.html
package-lock.json

Title ::Created Ui For Contact page +Storing in Backend +Acknowledgment 
Issue No. :Created Ui For Contact page +Storing in Backend +Acknowledgment +Email Template
Code Stack : Express 
Close #1206 
UI BEFORE:
Ui Now (video +Working):
https://github.com/user-attachments/assets/91f47483-2516-4ff4-bed6-3370fd8528c0
---
To Make it Work:
1) Add MongoDb URl in backend ->server.js
2) Add Your Email and ADD App password in   backend ->server.js
to generate app password :https://youtu.be/hXiPshHn9Pw?si=k-GdOSVsjFsHUV45 (refer this)
3) in terminal do
```
cd backend
node server.js
```
---

[Feature Request]: Want to Fix Ui Of Contact Page +Backend Integration #1206

---

assets/css/style.css

Title : screen width bug fixed
Issue No. : #1238
Code Stack : HTML
Close #1238 
https://github.com/user-attachments/assets/780b65b6-ab68-48bf-bb4d-6cda659df2c7

screen width bug fixed

---

RateUs.html
about old.html
about.html
contact.html
contributor.html
index.html

Title : Navigation Bar Buttons Not Redirecting Correctly & Overlapping Issue on Scroll
Issue No. : #1244
Tech Stack : MEARN (HTML)
Close #1244 
https://github.com/user-attachments/assets/b6313320-8cbc-4262-a387-f89fab2375a2

Navigate back to Home page, Feature added

---

assets/css/style.css
backend/server.js

Title :
Issue No. : #1285 
Close #1285
https://github.com/user-attachments/assets/4e30739b-3759-4c8a-a76a-ab5d21308c7e

Fix: Search Bar text not visible while searching #1285

---

contributor.html

Title : Added Cursor Animation | Issue #1243
Issue No. : #1243 
Tech Stack : 
https://github.com/user-attachments/assets/53826df8-5f32-41ff-aba8-9c704a6b2357
Close #1243 

Added Cursor Animation | Issue #1243

---

assets/css/contributors.css
assets/js/contributors.js
contributor.html

Title :Enhanced the UI of the contributors page
Issue No. : #1265 
Tech Stack : 
Close #1265
https://github.com/user-attachments/assets/c86b864b-338b-4ba1-af3d-7b59ed26e18a
@apu52 Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.
I have put so much efforts to this ui design to please give it a level 3 else it is upto you i can only suggest.

Enhanced the UI of the contributors page

---

RateUs.html

Title : Feedback from button enhanced
Issue No. : #1327 
Tech Stack : HTML, CSS
https://github.com/user-attachments/assets/29d519d7-0c24-4f0f-8243-6418c1e6ce6f

Feedback page  button enhnaced

---

backend/server.js
index.html

Fix Issue No. : #1331 
Title : Navbar Hamburger Menu Not Working in Mobile View
Tech Stack : CSS and JavaScript
Close #1331 
Tablet view: 
https://github.com/user-attachments/assets/97ad666b-06db-4f02-bbc6-fe881ca64214
Mobile view:
https://github.com/user-attachments/assets/6cc48760-6f92-4779-9c88-1d2359f75fd2

Make hamburger menu functional on smaller screens

---

RateUs.html
backend/controllers/feedback.js
backend/model/feedback.model.js
backend/server.js
backend/services/emailService.js

Title :Rate us
Issue No. : issue #1338 
Tech Stack : nodemailer, express, mongodb, html
Close #1338 

Add Rate us Implementation

---

assets/js/contactus.js
backend/.env.example
backend/controllers/contactus.js
backend/server.js
contact.html

Title : Contact us Implementation
Issue No. : 1345
Tech Stack : nodemailer, js 
Close #1345 

ADD Contact us Implementation

---

assets/js/index.js
index.html
projectData.json

Title : Filter
Issue No. : #1310
Tech Stack : JS
Close #1310

Request for "Filter" Feature for filtering the listing.

---

assets/css/contributors.css

Title : [Feature Request]: fix the contribution page, check description #1355 
Issue No. : #1355 
Tech Stack : CSS
Close #1355 
https://github.com/user-attachments/assets/fe0b8186-a43e-4e87-98e6-baffb0ff2571

 [Feature Request]: fix the contribution page, check description #1355 

---

Projects/Bake_website/menu.css
Projects/Bake_website/style.css
about.html
assets/css/style.css
assets/css/themeToggle.css
assets/js/subscribe.js
assets/js/toggletheme.js
backend/package-lock.json
backend/package.json
contact.html
contributor.html
index.html
style.css

Enhancement of Logo and Addition of Copyright Tag Under the Privacy Notice and Copyright Policy
Title : Enhancement of Logo and Addition of Copyright Tag
Issue No. : #1364 
Tech Stack : 

Enhancement of Logo and Addition of Copyright Tag #1364

---

index.html

Title : Navbar update
Issue No. : #1366
Tech Stack : Html,css
Close #1366 
Before:
- light mode navbar not visible
- dark mode incomplete blur effect
After:
- light mode navbar visible
- dark mode complete blur effect

Navbar update

---

contact.html

Title : added hovering effect on contact page on images of owners and #871
Issue No. : #871
Tech Stack : HTML, CSS
Close #<871>
- [ X] Feature enhancement
https://github.com/user-attachments/assets/84e7b6f1-e735-4f69-80b5-d25797074340
- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have gone through the  `contributing.md` file before contributing
- [ X] I have Starred the Repository.
- [ X] I have made my Commits(of new project) under the  `Projects` folder
- [X ] I have created a helpful and easy to understand `README.md`
- [ X] i have added the image of my project under `asstes/img` folder
Added hover effect on the images of contact us page.
***Are you …

fix: added hovering effect on contact page on images of owners #871

---

style.css

Title :Added style for navbar for small screen sizes. 
Issue No. :#1381
Tech Stack : HTML, CSS ,JS 
Close #1381 
https://github.com/user-attachments/assets/627629a1-c42c-4c04-bd7b-4aee8658884f

addded some styles in navbar for small screen sizes

---

RateUs.html
contributor.html
projectData.json
style.css

Title :  Modified  Some broken links in website. 
Issue No. :#1383
Close #1383
Tech Stack : HTML, CSS , JS

added some broken links

---

RateUs.html
contributor.html
copyright.html
index.html
style.css

Fixed the bug of navigation bar not having a background, making the navigation buttons interfere with the website's content.
Title : copywrite.html NavBar fix
Issue No. : 1375
Tech Stack : HTML, CSS
Close #1375 
- [ X ] Feature enhancement
https://github.com/user-attachments/assets/6b0c66a0-27cd-465d-b307-8a0d3336bfc0

Issue : 1375

---

contributor.html

Title : Contributors page was fixed / made . previously it was not able to show it all the contributors . 
Issue No. :  #1399 
Tech Stack : Javascript , html , css .  
reference :  [https://stackoverflow.com/questions/68607241/how-to-display-the-contributors-of-a-github-repository](url)
Close #1399 
Issue fixed 
https://github.com/user-attachments/assets/5440b243-d978-4ba3-a29b-0a300feafe95

contributorspage-fixed
